### ISSUE TITLE
Duping glitch with combined backpack[BUG] 

### ISSUE THREAD

**Issue by Aesopblock** [divisionind/BackpacksRemastered#1]
**Describe the bug**bes
You can dupe entire backpacks and the items inside them with 2 combined Backpacks
**To Reproduce**
1. get a large backpack and two(2) combined backpacks
2. combine one (1) of the combined backpacks with the large backpack
3. now combine the both of the combined backpacks, the empty combined backpack needs to be in the middle of and the combined backpack with the large backpack inside on the right middle field of the crafting bench
4. if you open the combined backpack within the combined backpack, you can just pull the backpack out and put it in your inventory close the overlay and repeat.

**Expected behavior**
You either shouldn't be able at all to combine two (2) combined backpacks with each other, or you should be able to open the large backpack inside of the 2nd combined backpack within the combined backpack. 

**Screenshots**
https://imgur.com/a/AE1BiRG
**Version info**
CraftBukkit version git-Bukkit-ba575a5 (MC:1.14.2)

**Comment by drew6017** [comment]
Looking into it

**Comment by drew6017** [comment]
Ended up having time to look at it today. The issue stems from the backpack inventory "tagging" and opening/closing system. I've been meaning to work on it for a while now but haven't had time because of school. 

As a temporary fix I am just going to disable putting combined backpacks in other combined backpacks. Thanks for the report!

Fixed as of 2019.1.6! [see commit](https://github.com/divisionind/BackpacksRemastered/commit/d62f755d4de1a5fb563685f38f23eb9a04d76a3a)
