### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ToshieCosed** [divisionind/BackpacksRemastered#4]
**Describe the bug**
LINKED backpack doesn't work cross-world or even too far outside of certain chunks in Spigot 1.14.4

**To Reproduce**
Make a linked backpack.
Link it to a chest first.
Then link it to a key.
Open it near the chest. It works.
Open it a few blocks away from the chest. It works.
Teleport above the chest if underground. It works.
Start travelling, about 100 blocks, it works.
About 200 blocks.. ehh.. kinda works.
Go too far? Sorry the edge chunks have unloaded where the chest lives and... BROKEN.
It opens for a split second then closes. Doesn't work anymore.

**Expected behavior**
The distance the player is away from the chunk where the chest the backpack is linked to should not matter. I should be able to go cross-dimension, cross-world, the_end, the nether, or overworld, I should be able to travel 200,000 blocks away from the chunk where the linked chest lives and still have a working inventory of that chest. Please fix.

**Screenshots**

**Version info**
SpigotMC 1.14.4

**Additional context**
Nothing else to add, other than the fact I am opped.

**Comment by drew6017** [comment]
The linked backpack pulls inventory data directly from world regions and sends packets to nearby players for the chest open effect. **It is not dependent on chunk loading what-so-ever.** Testing on both spigot and craftbukkit 1.14.4 with BackpacksRemastered-2019.1.6 showed no issues opening the backpack in the nether, end, and 20k blocks away from the chest location in the overworld. This is not a bug. If you really are experiencing issues, it is due to incompatibilities with other plugins.
